// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alpacalabs/confirmation/v1/api.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConfirmEmailAddressRequest struct {
	// a randomly generated code
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// the email address associated with the code
	EmailAddressId       string   `protobuf:"bytes,2,opt,name=email_address_id,json=emailAddressId,proto3" json:"email_address_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmEmailAddressRequest) Reset()         { *m = ConfirmEmailAddressRequest{} }
func (m *ConfirmEmailAddressRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmEmailAddressRequest) ProtoMessage()    {}
func (*ConfirmEmailAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11f033f3a571f82c, []int{0}
}

func (m *ConfirmEmailAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmEmailAddressRequest.Unmarshal(m, b)
}
func (m *ConfirmEmailAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmEmailAddressRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmEmailAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmEmailAddressRequest.Merge(m, src)
}
func (m *ConfirmEmailAddressRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmEmailAddressRequest.Size(m)
}
func (m *ConfirmEmailAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmEmailAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmEmailAddressRequest proto.InternalMessageInfo

func (m *ConfirmEmailAddressRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ConfirmEmailAddressRequest) GetEmailAddressId() string {
	if m != nil {
		return m.EmailAddressId
	}
	return ""
}

type ConfirmEmailAddressResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmEmailAddressResponse) Reset()         { *m = ConfirmEmailAddressResponse{} }
func (m *ConfirmEmailAddressResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmEmailAddressResponse) ProtoMessage()    {}
func (*ConfirmEmailAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_11f033f3a571f82c, []int{1}
}

func (m *ConfirmEmailAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmEmailAddressResponse.Unmarshal(m, b)
}
func (m *ConfirmEmailAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmEmailAddressResponse.Marshal(b, m, deterministic)
}
func (m *ConfirmEmailAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmEmailAddressResponse.Merge(m, src)
}
func (m *ConfirmEmailAddressResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmEmailAddressResponse.Size(m)
}
func (m *ConfirmEmailAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmEmailAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmEmailAddressResponse proto.InternalMessageInfo

type ConfirmPhoneNumberRequest struct {
	// a randomly generated code
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// the email address associated with the code
	PhoneNumberId        string   `protobuf:"bytes,2,opt,name=phone_number_id,json=phoneNumberId,proto3" json:"phone_number_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmPhoneNumberRequest) Reset()         { *m = ConfirmPhoneNumberRequest{} }
func (m *ConfirmPhoneNumberRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmPhoneNumberRequest) ProtoMessage()    {}
func (*ConfirmPhoneNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11f033f3a571f82c, []int{2}
}

func (m *ConfirmPhoneNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmPhoneNumberRequest.Unmarshal(m, b)
}
func (m *ConfirmPhoneNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmPhoneNumberRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmPhoneNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmPhoneNumberRequest.Merge(m, src)
}
func (m *ConfirmPhoneNumberRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmPhoneNumberRequest.Size(m)
}
func (m *ConfirmPhoneNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmPhoneNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmPhoneNumberRequest proto.InternalMessageInfo

func (m *ConfirmPhoneNumberRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ConfirmPhoneNumberRequest) GetPhoneNumberId() string {
	if m != nil {
		return m.PhoneNumberId
	}
	return ""
}

type ConfirmPhoneNumberResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmPhoneNumberResponse) Reset()         { *m = ConfirmPhoneNumberResponse{} }
func (m *ConfirmPhoneNumberResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmPhoneNumberResponse) ProtoMessage()    {}
func (*ConfirmPhoneNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_11f033f3a571f82c, []int{3}
}

func (m *ConfirmPhoneNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmPhoneNumberResponse.Unmarshal(m, b)
}
func (m *ConfirmPhoneNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmPhoneNumberResponse.Marshal(b, m, deterministic)
}
func (m *ConfirmPhoneNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmPhoneNumberResponse.Merge(m, src)
}
func (m *ConfirmPhoneNumberResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmPhoneNumberResponse.Size(m)
}
func (m *ConfirmPhoneNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmPhoneNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmPhoneNumberResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ConfirmEmailAddressRequest)(nil), "alpacalabs.confirmation.v1.ConfirmEmailAddressRequest")
	proto.RegisterType((*ConfirmEmailAddressResponse)(nil), "alpacalabs.confirmation.v1.ConfirmEmailAddressResponse")
	proto.RegisterType((*ConfirmPhoneNumberRequest)(nil), "alpacalabs.confirmation.v1.ConfirmPhoneNumberRequest")
	proto.RegisterType((*ConfirmPhoneNumberResponse)(nil), "alpacalabs.confirmation.v1.ConfirmPhoneNumberResponse")
}

func init() {
	proto.RegisterFile("alpacalabs/confirmation/v1/api.proto", fileDescriptor_11f033f3a571f82c)
}

var fileDescriptor_11f033f3a571f82c = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcd, 0x4a, 0xfb, 0x40,
	0x14, 0xc5, 0xff, 0xc9, 0x5f, 0x04, 0x07, 0xfc, 0x1a, 0x37, 0x35, 0x7e, 0x20, 0x41, 0xa4, 0x9b,
	0x4e, 0x48, 0xc5, 0xba, 0x6e, 0x8b, 0x8b, 0x4a, 0x91, 0x52, 0xa1, 0x42, 0x29, 0x84, 0x49, 0x72,
	0x6d, 0x07, 0x9a, 0xcc, 0x98, 0x49, 0xfb, 0x06, 0x82, 0xcf, 0xe1, 0x4a, 0x7c, 0x0b, 0xb7, 0x3e,
	0x95, 0x64, 0x52, 0x9b, 0x91, 0xda, 0x62, 0x77, 0xc9, 0x9c, 0x73, 0x7f, 0x67, 0xe6, 0x70, 0xd1,
	0x39, 0x1d, 0x0b, 0x1a, 0xd0, 0x31, 0xf5, 0xa5, 0x13, 0xf0, 0xf8, 0x91, 0x25, 0x11, 0x4d, 0x19,
	0x8f, 0x9d, 0xa9, 0xeb, 0x50, 0xc1, 0x88, 0x48, 0x78, 0xca, 0xb1, 0x55, 0xb8, 0x88, 0xee, 0x22,
	0x53, 0xd7, 0xaa, 0xae, 0x20, 0xe8, 0xff, 0x5e, 0xc0, 0x43, 0xc8, 0x79, 0x76, 0x1f, 0x59, 0xcd,
	0x5c, 0xba, 0x89, 0x28, 0x1b, 0xd7, 0xc3, 0x30, 0x01, 0x29, 0xbb, 0xf0, 0x34, 0x01, 0x99, 0x62,
	0x8c, 0x36, 0x32, 0x6f, 0xc9, 0x38, 0x33, 0xca, 0x5b, 0x5d, 0xf5, 0x8d, 0xcb, 0x68, 0x0f, 0x32,
	0xab, 0x47, 0x73, 0xaf, 0xc7, 0xc2, 0x92, 0xa9, 0xf4, 0x1d, 0xd0, 0x10, 0xad, 0xd0, 0x3e, 0x41,
	0x47, 0xbf, 0xb2, 0xa5, 0xe0, 0xb1, 0x04, 0xfb, 0x01, 0x1d, 0xce, 0xe4, 0xce, 0x88, 0xc7, 0x70,
	0x37, 0x89, 0x7c, 0x48, 0x56, 0x25, 0x5f, 0xa0, 0x5d, 0x91, 0x39, 0xbd, 0x58, 0x59, 0x8b, 0xe0,
	0x6d, 0x51, 0x00, 0x5a, 0xa1, 0x7d, 0x3c, 0x7f, 0xd3, 0x0f, 0x70, 0x1e, 0x5b, 0x7d, 0x33, 0xd1,
	0x41, 0x53, 0x6b, 0xe3, 0x1e, 0x92, 0x29, 0x0b, 0x00, 0xbf, 0x18, 0xf3, 0x73, 0xfd, 0xba, 0xb8,
	0x46, 0x96, 0x57, 0x4e, 0x96, 0x77, 0x67, 0x5d, 0xaf, 0x3d, 0x37, 0xeb, 0xe5, 0x1f, 0x7e, 0x36,
	0x10, 0x5e, 0x7c, 0x01, 0xbe, 0xfa, 0x03, 0x71, 0xb1, 0x4a, 0xab, 0xb6, 0xee, 0xd8, 0xf7, 0x3d,
	0x1a, 0x1f, 0x06, 0x3a, 0x0d, 0x78, 0xb4, 0x62, 0xbe, 0xb1, 0xaf, 0x57, 0xd9, 0xc9, 0x56, 0xaa,
	0x63, 0xf4, 0x6f, 0x87, 0x2c, 0x1d, 0x4d, 0x7c, 0x12, 0xf0, 0xc8, 0xa9, 0xab, 0xd9, 0x76, 0xb6,
	0x93, 0x6a, 0xe3, 0x12, 0x10, 0xbc, 0xa2, 0x53, 0x2a, 0x43, 0xee, 0x2c, 0x5f, 0xdc, 0x57, 0xf3,
	0x7f, 0xbd, 0xdd, 0x7c, 0x37, 0xad, 0x82, 0x43, 0xf4, 0x48, 0xd2, 0x73, 0x3f, 0x75, 0x71, 0xa0,
	0x8b, 0x83, 0x9e, 0xeb, 0x6f, 0xaa, 0xd4, 0xcb, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa8, 0xe7,
	0x61, 0x63, 0x5f, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConfirmationServiceClient is the client API for ConfirmationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConfirmationServiceClient interface {
	ConfirmEmailAddress(ctx context.Context, in *ConfirmEmailAddressRequest, opts ...grpc.CallOption) (*ConfirmEmailAddressResponse, error)
	ConfirmPhoneNumber(ctx context.Context, in *ConfirmPhoneNumberRequest, opts ...grpc.CallOption) (*ConfirmPhoneNumberResponse, error)
}

type confirmationServiceClient struct {
	cc *grpc.ClientConn
}

func NewConfirmationServiceClient(cc *grpc.ClientConn) ConfirmationServiceClient {
	return &confirmationServiceClient{cc}
}

func (c *confirmationServiceClient) ConfirmEmailAddress(ctx context.Context, in *ConfirmEmailAddressRequest, opts ...grpc.CallOption) (*ConfirmEmailAddressResponse, error) {
	out := new(ConfirmEmailAddressResponse)
	err := c.cc.Invoke(ctx, "/alpacalabs.confirmation.v1.ConfirmationService/ConfirmEmailAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *confirmationServiceClient) ConfirmPhoneNumber(ctx context.Context, in *ConfirmPhoneNumberRequest, opts ...grpc.CallOption) (*ConfirmPhoneNumberResponse, error) {
	out := new(ConfirmPhoneNumberResponse)
	err := c.cc.Invoke(ctx, "/alpacalabs.confirmation.v1.ConfirmationService/ConfirmPhoneNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfirmationServiceServer is the server API for ConfirmationService service.
type ConfirmationServiceServer interface {
	ConfirmEmailAddress(context.Context, *ConfirmEmailAddressRequest) (*ConfirmEmailAddressResponse, error)
	ConfirmPhoneNumber(context.Context, *ConfirmPhoneNumberRequest) (*ConfirmPhoneNumberResponse, error)
}

func RegisterConfirmationServiceServer(s *grpc.Server, srv ConfirmationServiceServer) {
	s.RegisterService(&_ConfirmationService_serviceDesc, srv)
}

func _ConfirmationService_ConfirmEmailAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmEmailAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfirmationServiceServer).ConfirmEmailAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alpacalabs.confirmation.v1.ConfirmationService/ConfirmEmailAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfirmationServiceServer).ConfirmEmailAddress(ctx, req.(*ConfirmEmailAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfirmationService_ConfirmPhoneNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPhoneNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfirmationServiceServer).ConfirmPhoneNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alpacalabs.confirmation.v1.ConfirmationService/ConfirmPhoneNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfirmationServiceServer).ConfirmPhoneNumber(ctx, req.(*ConfirmPhoneNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConfirmationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "alpacalabs.confirmation.v1.ConfirmationService",
	HandlerType: (*ConfirmationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfirmEmailAddress",
			Handler:    _ConfirmationService_ConfirmEmailAddress_Handler,
		},
		{
			MethodName: "ConfirmPhoneNumber",
			Handler:    _ConfirmationService_ConfirmPhoneNumber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alpacalabs/confirmation/v1/api.proto",
}
