// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alpacalabs/confirmation/v1/api_create.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateEmailAddressConfirmationCode struct {
	EmailAddressId       string   `protobuf:"bytes,1,opt,name=email_address_id,json=emailAddressId,proto3" json:"email_address_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmailAddressConfirmationCode) Reset()         { *m = CreateEmailAddressConfirmationCode{} }
func (m *CreateEmailAddressConfirmationCode) String() string { return proto.CompactTextString(m) }
func (*CreateEmailAddressConfirmationCode) ProtoMessage()    {}
func (*CreateEmailAddressConfirmationCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_d83313b0b285105e, []int{0}
}

func (m *CreateEmailAddressConfirmationCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmailAddressConfirmationCode.Unmarshal(m, b)
}
func (m *CreateEmailAddressConfirmationCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmailAddressConfirmationCode.Marshal(b, m, deterministic)
}
func (m *CreateEmailAddressConfirmationCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmailAddressConfirmationCode.Merge(m, src)
}
func (m *CreateEmailAddressConfirmationCode) XXX_Size() int {
	return xxx_messageInfo_CreateEmailAddressConfirmationCode.Size(m)
}
func (m *CreateEmailAddressConfirmationCode) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmailAddressConfirmationCode.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmailAddressConfirmationCode proto.InternalMessageInfo

func (m *CreateEmailAddressConfirmationCode) GetEmailAddressId() string {
	if m != nil {
		return m.EmailAddressId
	}
	return ""
}

type CreatePhoneNumberConfirmationCode struct {
	PhoneNumberId        string   `protobuf:"bytes,1,opt,name=phone_number_id,json=phoneNumberId,proto3" json:"phone_number_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePhoneNumberConfirmationCode) Reset()         { *m = CreatePhoneNumberConfirmationCode{} }
func (m *CreatePhoneNumberConfirmationCode) String() string { return proto.CompactTextString(m) }
func (*CreatePhoneNumberConfirmationCode) ProtoMessage()    {}
func (*CreatePhoneNumberConfirmationCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_d83313b0b285105e, []int{1}
}

func (m *CreatePhoneNumberConfirmationCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePhoneNumberConfirmationCode.Unmarshal(m, b)
}
func (m *CreatePhoneNumberConfirmationCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePhoneNumberConfirmationCode.Marshal(b, m, deterministic)
}
func (m *CreatePhoneNumberConfirmationCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePhoneNumberConfirmationCode.Merge(m, src)
}
func (m *CreatePhoneNumberConfirmationCode) XXX_Size() int {
	return xxx_messageInfo_CreatePhoneNumberConfirmationCode.Size(m)
}
func (m *CreatePhoneNumberConfirmationCode) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePhoneNumberConfirmationCode.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePhoneNumberConfirmationCode proto.InternalMessageInfo

func (m *CreatePhoneNumberConfirmationCode) GetPhoneNumberId() string {
	if m != nil {
		return m.PhoneNumberId
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateEmailAddressConfirmationCode)(nil), "alpacalabs.confirmation.v1.CreateEmailAddressConfirmationCode")
	proto.RegisterType((*CreatePhoneNumberConfirmationCode)(nil), "alpacalabs.confirmation.v1.CreatePhoneNumberConfirmationCode")
}

func init() {
	proto.RegisterFile("alpacalabs/confirmation/v1/api_create.proto", fileDescriptor_d83313b0b285105e)
}

var fileDescriptor_d83313b0b285105e = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4e, 0xcc, 0x29, 0x48,
	0x4c, 0x4e, 0xcc, 0x49, 0x4c, 0x2a, 0xd6, 0x4f, 0xce, 0xcf, 0x4b, 0xcb, 0x2c, 0xca, 0x4d, 0x2c,
	0xc9, 0xcc, 0xcf, 0xd3, 0x2f, 0x33, 0xd4, 0x4f, 0x2c, 0xc8, 0x8c, 0x4f, 0x2e, 0x4a, 0x4d, 0x2c,
	0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x42, 0x28, 0xd6, 0x43, 0x56, 0xac, 0x57,
	0x66, 0xa8, 0xe4, 0xc7, 0xa5, 0xe4, 0x0c, 0x56, 0xeb, 0x9a, 0x9b, 0x98, 0x99, 0xe3, 0x98, 0x92,
	0x52, 0x94, 0x5a, 0x5c, 0xec, 0x8c, 0xa4, 0xc8, 0x39, 0x3f, 0x25, 0x55, 0x48, 0x83, 0x4b, 0x20,
	0x15, 0x24, 0x1f, 0x9f, 0x08, 0x51, 0x10, 0x9f, 0x99, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19,
	0xc4, 0x97, 0x8a, 0xa4, 0xcf, 0x33, 0x45, 0xc9, 0x9b, 0x4b, 0x11, 0x62, 0x5e, 0x40, 0x46, 0x7e,
	0x5e, 0xaa, 0x5f, 0x69, 0x6e, 0x52, 0x6a, 0x11, 0x86, 0x71, 0x6a, 0x5c, 0xfc, 0x05, 0x20, 0xe9,
	0xf8, 0x3c, 0xb0, 0x3c, 0xc2, 0x34, 0xde, 0x02, 0x84, 0x2e, 0xcf, 0x14, 0xa7, 0x83, 0x8c, 0x5c,
	0x72, 0xc9, 0xf9, 0xb9, 0x7a, 0xb8, 0xdd, 0xef, 0x24, 0x88, 0x6c, 0x78, 0x00, 0xc8, 0xbb, 0x01,
	0x8c, 0x51, 0x5e, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0x8e, 0x60,
	0xbd, 0x3e, 0xa0, 0x80, 0x02, 0x87, 0x46, 0x51, 0x6a, 0x41, 0xbe, 0x2e, 0xb2, 0x29, 0xba, 0xe9,
	0xf9, 0xfa, 0xb8, 0x43, 0x73, 0x11, 0x13, 0xb3, 0xa3, 0x8f, 0xf3, 0x2a, 0x26, 0x29, 0x84, 0x39,
	0x7a, 0xc8, 0x56, 0xea, 0x85, 0x19, 0x9e, 0x42, 0x96, 0x8c, 0x41, 0x96, 0x8c, 0x09, 0x33, 0x4c,
	0x62, 0x03, 0xdb, 0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x43, 0x0a, 0x31, 0xb2, 0x01,
	0x00, 0x00,
}
