// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alpacalabs/confirmation/v1/api_confirm.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConfirmEmailAddressRequest struct {
	// a randomly generated code
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// the email address associated with the code
	EmailAddressId       string   `protobuf:"bytes,2,opt,name=email_address_id,json=emailAddressId,proto3" json:"email_address_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmEmailAddressRequest) Reset()         { *m = ConfirmEmailAddressRequest{} }
func (m *ConfirmEmailAddressRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmEmailAddressRequest) ProtoMessage()    {}
func (*ConfirmEmailAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b194efb089d8157, []int{0}
}

func (m *ConfirmEmailAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmEmailAddressRequest.Unmarshal(m, b)
}
func (m *ConfirmEmailAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmEmailAddressRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmEmailAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmEmailAddressRequest.Merge(m, src)
}
func (m *ConfirmEmailAddressRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmEmailAddressRequest.Size(m)
}
func (m *ConfirmEmailAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmEmailAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmEmailAddressRequest proto.InternalMessageInfo

func (m *ConfirmEmailAddressRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ConfirmEmailAddressRequest) GetEmailAddressId() string {
	if m != nil {
		return m.EmailAddressId
	}
	return ""
}

type ConfirmEmailAddressResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmEmailAddressResponse) Reset()         { *m = ConfirmEmailAddressResponse{} }
func (m *ConfirmEmailAddressResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmEmailAddressResponse) ProtoMessage()    {}
func (*ConfirmEmailAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b194efb089d8157, []int{1}
}

func (m *ConfirmEmailAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmEmailAddressResponse.Unmarshal(m, b)
}
func (m *ConfirmEmailAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmEmailAddressResponse.Marshal(b, m, deterministic)
}
func (m *ConfirmEmailAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmEmailAddressResponse.Merge(m, src)
}
func (m *ConfirmEmailAddressResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmEmailAddressResponse.Size(m)
}
func (m *ConfirmEmailAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmEmailAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmEmailAddressResponse proto.InternalMessageInfo

type ConfirmPhoneNumberRequest struct {
	// a randomly generated code
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// the email address associated with the code
	PhoneNumberId        string   `protobuf:"bytes,2,opt,name=phone_number_id,json=phoneNumberId,proto3" json:"phone_number_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmPhoneNumberRequest) Reset()         { *m = ConfirmPhoneNumberRequest{} }
func (m *ConfirmPhoneNumberRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmPhoneNumberRequest) ProtoMessage()    {}
func (*ConfirmPhoneNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b194efb089d8157, []int{2}
}

func (m *ConfirmPhoneNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmPhoneNumberRequest.Unmarshal(m, b)
}
func (m *ConfirmPhoneNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmPhoneNumberRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmPhoneNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmPhoneNumberRequest.Merge(m, src)
}
func (m *ConfirmPhoneNumberRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmPhoneNumberRequest.Size(m)
}
func (m *ConfirmPhoneNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmPhoneNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmPhoneNumberRequest proto.InternalMessageInfo

func (m *ConfirmPhoneNumberRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ConfirmPhoneNumberRequest) GetPhoneNumberId() string {
	if m != nil {
		return m.PhoneNumberId
	}
	return ""
}

type ConfirmPhoneNumberResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmPhoneNumberResponse) Reset()         { *m = ConfirmPhoneNumberResponse{} }
func (m *ConfirmPhoneNumberResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmPhoneNumberResponse) ProtoMessage()    {}
func (*ConfirmPhoneNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b194efb089d8157, []int{3}
}

func (m *ConfirmPhoneNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmPhoneNumberResponse.Unmarshal(m, b)
}
func (m *ConfirmPhoneNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmPhoneNumberResponse.Marshal(b, m, deterministic)
}
func (m *ConfirmPhoneNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmPhoneNumberResponse.Merge(m, src)
}
func (m *ConfirmPhoneNumberResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmPhoneNumberResponse.Size(m)
}
func (m *ConfirmPhoneNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmPhoneNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmPhoneNumberResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ConfirmEmailAddressRequest)(nil), "alpacalabs.confirmation.v1.ConfirmEmailAddressRequest")
	proto.RegisterType((*ConfirmEmailAddressResponse)(nil), "alpacalabs.confirmation.v1.ConfirmEmailAddressResponse")
	proto.RegisterType((*ConfirmPhoneNumberRequest)(nil), "alpacalabs.confirmation.v1.ConfirmPhoneNumberRequest")
	proto.RegisterType((*ConfirmPhoneNumberResponse)(nil), "alpacalabs.confirmation.v1.ConfirmPhoneNumberResponse")
}

func init() {
	proto.RegisterFile("alpacalabs/confirmation/v1/api_confirm.proto", fileDescriptor_5b194efb089d8157)
}

var fileDescriptor_5b194efb089d8157 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xdd, 0x4a, 0xc3, 0x30,
	0x1c, 0xc5, 0x69, 0x15, 0xc1, 0x80, 0x5f, 0xbd, 0x9a, 0xf5, 0x03, 0xe9, 0x85, 0xec, 0xc2, 0xa5,
	0x14, 0x9f, 0xa0, 0x2b, 0x5e, 0x4c, 0x86, 0x94, 0x5d, 0x4c, 0x18, 0x83, 0x92, 0x36, 0x7f, 0xb7,
	0x40, 0xdb, 0x7f, 0x6c, 0xda, 0x3d, 0x90, 0x97, 0xbe, 0x85, 0xb7, 0x3e, 0x95, 0x34, 0x1d, 0x36,
	0x82, 0xdb, 0x5d, 0x38, 0xe7, 0xe4, 0x77, 0xc8, 0x09, 0x79, 0x60, 0xb9, 0x64, 0x19, 0xcb, 0x59,
	0xaa, 0xfc, 0x0c, 0xcb, 0x37, 0x51, 0x15, 0xac, 0x16, 0x58, 0xfa, 0x9b, 0xc0, 0x67, 0x52, 0x24,
	0x5b, 0x8d, 0xca, 0x0a, 0x6b, 0x74, 0xdc, 0x3e, 0x4d, 0xcd, 0x34, 0xdd, 0x04, 0xde, 0x82, 0xb8,
	0x51, 0x27, 0x3d, 0x15, 0x4c, 0xe4, 0x21, 0xe7, 0x15, 0x28, 0x35, 0x83, 0xf7, 0x06, 0x54, 0xed,
	0x38, 0xe4, 0x30, 0x43, 0x0e, 0x03, 0xeb, 0xce, 0x1a, 0x1e, 0xcf, 0xf4, 0xd9, 0x19, 0x92, 0x73,
	0x68, 0xa3, 0x09, 0xeb, 0xb2, 0x89, 0xe0, 0x03, 0x5b, 0xfb, 0xa7, 0x60, 0x20, 0x26, 0xdc, 0xbb,
	0x21, 0x57, 0xff, 0xb2, 0x95, 0xc4, 0x52, 0x81, 0xf7, 0x4a, 0x2e, 0xb7, 0x76, 0xbc, 0xc6, 0x12,
	0x5e, 0x9a, 0x22, 0x85, 0x6a, 0x5f, 0xf3, 0x3d, 0x39, 0x93, 0x6d, 0x32, 0x29, 0x75, 0xb4, 0x2f,
	0x3e, 0x91, 0x3d, 0x60, 0xc2, 0xbd, 0xeb, 0xdf, 0x37, 0xfd, 0x01, 0x77, 0xb5, 0xe3, 0x2f, 0x8b,
	0xdc, 0x66, 0x58, 0xd0, 0xdd, 0xa3, 0x8c, 0x2f, 0x22, 0x43, 0x88, 0xdb, 0x0d, 0x63, 0x6b, 0xf1,
	0xbc, 0x12, 0xf5, 0xba, 0x49, 0x69, 0x86, 0x85, 0x1f, 0xea, 0xbb, 0xd3, 0x76, 0x7e, 0x3d, 0x71,
	0x05, 0x12, 0x47, 0x26, 0x65, 0xb4, 0x42, 0x7f, 0xf7, 0x1f, 0x7d, 0xd8, 0x07, 0xe1, 0x34, 0xfa,
	0xb4, 0xdd, 0x9e, 0x43, 0xcd, 0x4a, 0x3a, 0x0f, 0xbe, 0x4d, 0x73, 0x69, 0x9a, 0xcb, 0x79, 0x90,
	0x1e, 0xe9, 0xd6, 0xc7, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8a, 0xfe, 0x3b, 0x51, 0x08, 0x02,
	0x00, 0x00,
}
