// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alpacalabs/confirmation/v1/confirmation_code.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmailAddressConfirmationCode struct {
	// primary key
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// the email address associated with this code
	EmailAddressId string `protobuf:"bytes,2,opt,name=email_address_id,json=emailAddressId,proto3" json:"email_address_id,omitempty"`
	// a randomly generated code
	Code string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	// when the code was generated
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// when the code expires
	ExpiresAt *timestamp.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// indicates whether a code has been used. Once used, all codes
	// that belong to the account become stale.
	Used bool `protobuf:"varint,6,opt,name=used,proto3" json:"used,omitempty"`
	// if true, this code cannot be used. When a user uses a code,
	// all previously issued codes are rendered stale.
	Stale                bool     `protobuf:"varint,7,opt,name=stale,proto3" json:"stale,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailAddressConfirmationCode) Reset()         { *m = EmailAddressConfirmationCode{} }
func (m *EmailAddressConfirmationCode) String() string { return proto.CompactTextString(m) }
func (*EmailAddressConfirmationCode) ProtoMessage()    {}
func (*EmailAddressConfirmationCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2e6aa38adcffcd8, []int{0}
}

func (m *EmailAddressConfirmationCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailAddressConfirmationCode.Unmarshal(m, b)
}
func (m *EmailAddressConfirmationCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailAddressConfirmationCode.Marshal(b, m, deterministic)
}
func (m *EmailAddressConfirmationCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailAddressConfirmationCode.Merge(m, src)
}
func (m *EmailAddressConfirmationCode) XXX_Size() int {
	return xxx_messageInfo_EmailAddressConfirmationCode.Size(m)
}
func (m *EmailAddressConfirmationCode) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailAddressConfirmationCode.DiscardUnknown(m)
}

var xxx_messageInfo_EmailAddressConfirmationCode proto.InternalMessageInfo

func (m *EmailAddressConfirmationCode) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EmailAddressConfirmationCode) GetEmailAddressId() string {
	if m != nil {
		return m.EmailAddressId
	}
	return ""
}

func (m *EmailAddressConfirmationCode) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *EmailAddressConfirmationCode) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *EmailAddressConfirmationCode) GetExpiresAt() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

func (m *EmailAddressConfirmationCode) GetUsed() bool {
	if m != nil {
		return m.Used
	}
	return false
}

func (m *EmailAddressConfirmationCode) GetStale() bool {
	if m != nil {
		return m.Stale
	}
	return false
}

type PhoneNumberConfirmationCode struct {
	// primary key
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// the phone number associated with this code
	PhoneNumberId string `protobuf:"bytes,2,opt,name=phone_number_id,json=phoneNumberId,proto3" json:"phone_number_id,omitempty"`
	// a randomly generated code
	Code string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	// when the code was generated
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// when the code expires
	ExpiresAt *timestamp.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// indicates whether a code has been used. Once used, all codes
	// that belong to the account become stale.
	Used bool `protobuf:"varint,6,opt,name=used,proto3" json:"used,omitempty"`
	// if true, this code cannot be used. When a user uses a code,
	// all previously issued codes are rendered stale.
	Stale                bool     `protobuf:"varint,7,opt,name=stale,proto3" json:"stale,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneNumberConfirmationCode) Reset()         { *m = PhoneNumberConfirmationCode{} }
func (m *PhoneNumberConfirmationCode) String() string { return proto.CompactTextString(m) }
func (*PhoneNumberConfirmationCode) ProtoMessage()    {}
func (*PhoneNumberConfirmationCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2e6aa38adcffcd8, []int{1}
}

func (m *PhoneNumberConfirmationCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneNumberConfirmationCode.Unmarshal(m, b)
}
func (m *PhoneNumberConfirmationCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneNumberConfirmationCode.Marshal(b, m, deterministic)
}
func (m *PhoneNumberConfirmationCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneNumberConfirmationCode.Merge(m, src)
}
func (m *PhoneNumberConfirmationCode) XXX_Size() int {
	return xxx_messageInfo_PhoneNumberConfirmationCode.Size(m)
}
func (m *PhoneNumberConfirmationCode) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneNumberConfirmationCode.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneNumberConfirmationCode proto.InternalMessageInfo

func (m *PhoneNumberConfirmationCode) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PhoneNumberConfirmationCode) GetPhoneNumberId() string {
	if m != nil {
		return m.PhoneNumberId
	}
	return ""
}

func (m *PhoneNumberConfirmationCode) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *PhoneNumberConfirmationCode) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *PhoneNumberConfirmationCode) GetExpiresAt() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

func (m *PhoneNumberConfirmationCode) GetUsed() bool {
	if m != nil {
		return m.Used
	}
	return false
}

func (m *PhoneNumberConfirmationCode) GetStale() bool {
	if m != nil {
		return m.Stale
	}
	return false
}

func init() {
	proto.RegisterType((*EmailAddressConfirmationCode)(nil), "alpacalabs.confirmation.v1.EmailAddressConfirmationCode")
	proto.RegisterType((*PhoneNumberConfirmationCode)(nil), "alpacalabs.confirmation.v1.PhoneNumberConfirmationCode")
}

func init() {
	proto.RegisterFile("alpacalabs/confirmation/v1/confirmation_code.proto", fileDescriptor_e2e6aa38adcffcd8)
}

var fileDescriptor_e2e6aa38adcffcd8 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x52, 0xcb, 0x6a, 0xdb, 0x40,
	0x14, 0x45, 0xf2, 0xa3, 0xf5, 0x94, 0xba, 0xad, 0xe8, 0x42, 0xa8, 0xa5, 0x35, 0x5e, 0x14, 0x6d,
	0x3c, 0x42, 0xee, 0x2a, 0x4b, 0xd9, 0x64, 0x91, 0x60, 0x82, 0x31, 0xc1, 0x8b, 0x60, 0x10, 0x23,
	0xcd, 0xb5, 0x3c, 0x20, 0x69, 0x84, 0x34, 0x32, 0xf9, 0x85, 0x40, 0xbe, 0x22, 0xcb, 0xfc, 0x45,
	0xb6, 0xf9, 0xaa, 0x30, 0x23, 0x1b, 0x4d, 0x16, 0xc6, 0xeb, 0xec, 0xe6, 0xce, 0x79, 0xdc, 0xc3,
	0xe1, 0xa2, 0x29, 0x49, 0x0b, 0x12, 0x93, 0x94, 0x44, 0x95, 0x17, 0xf3, 0x7c, 0xcb, 0xca, 0x8c,
	0x08, 0xc6, 0x73, 0x6f, 0xef, 0xbf, 0x9b, 0xc3, 0x98, 0x53, 0xc0, 0x45, 0xc9, 0x05, 0xb7, 0x9c,
	0x56, 0x83, 0x75, 0x0e, 0xde, 0xfb, 0xce, 0xdf, 0x84, 0xf3, 0x24, 0x05, 0x4f, 0x31, 0xa3, 0x7a,
	0xeb, 0x09, 0x96, 0x41, 0x25, 0x48, 0x56, 0x34, 0xe2, 0xf1, 0xa3, 0x89, 0x7e, 0x5f, 0x66, 0x84,
	0xa5, 0x01, 0xa5, 0x25, 0x54, 0xd5, 0x5c, 0x33, 0x98, 0x73, 0x0a, 0xd6, 0x10, 0x99, 0x8c, 0xda,
	0xc6, 0xc8, 0x70, 0x07, 0x2b, 0x93, 0x51, 0xcb, 0x45, 0xdf, 0x41, 0xf2, 0x43, 0xd2, 0x08, 0x42,
	0x46, 0x6d, 0x53, 0xa1, 0x43, 0xd0, 0x7c, 0xae, 0xa8, 0x65, 0xa1, 0xae, 0x4c, 0x69, 0x77, 0x14,
	0xaa, 0xde, 0xd6, 0x05, 0x42, 0x71, 0x09, 0x44, 0x00, 0x0d, 0x89, 0xb0, 0xbb, 0x23, 0xc3, 0xfd,
	0x32, 0x75, 0x70, 0x13, 0x12, 0x1f, 0x43, 0xe2, 0xdb, 0x63, 0xc8, 0xd5, 0xe0, 0xc0, 0x0e, 0x84,
	0x94, 0xc2, 0x7d, 0xc1, 0x4a, 0xa8, 0xa4, 0xb4, 0x77, 0x5e, 0x7a, 0x60, 0x07, 0x42, 0x26, 0xa9,
	0x2b, 0xa0, 0x76, 0x7f, 0x64, 0xb8, 0x9f, 0x57, 0xea, 0x6d, 0xfd, 0x44, 0xbd, 0x4a, 0x90, 0x14,
	0xec, 0x4f, 0xea, 0xb3, 0x19, 0xc6, 0x0f, 0x26, 0xfa, 0xb5, 0xdc, 0xf1, 0x1c, 0x6e, 0xea, 0x2c,
	0x82, 0xf2, 0x6c, 0x1b, 0xff, 0xd0, 0xb7, 0x42, 0xd2, 0xc3, 0x5c, 0xf1, 0xdb, 0x32, 0xbe, 0x16,
	0xad, 0xcb, 0xc7, 0xec, 0x62, 0xf6, 0x62, 0xa0, 0x3f, 0x31, 0xcf, 0xf0, 0xe9, 0xf3, 0x9a, 0xfd,
	0xd0, 0x0b, 0x5a, 0xca, 0xbd, 0x4b, 0xe3, 0xee, 0x3a, 0x61, 0x62, 0x57, 0x47, 0x38, 0xe6, 0x99,
	0x17, 0x28, 0xed, 0x42, 0x9e, 0xb3, 0x8a, 0x55, 0x42, 0xc1, 0x27, 0xba, 0xcb, 0x24, 0xe1, 0xde,
	0xe9, 0x9b, 0x7f, 0x32, 0x3b, 0xc1, 0x62, 0xfe, 0x6c, 0x3a, 0xad, 0x0f, 0xd6, 0x57, 0xe2, 0xb5,
	0xff, 0xaa, 0x83, 0x1b, 0x1d, 0xdc, 0xac, 0xfd, 0xa8, 0xaf, 0xb6, 0xfe, 0x7f, 0x0b, 0x00, 0x00,
	0xff, 0xff, 0x70, 0x49, 0x2c, 0xfa, 0x58, 0x03, 0x00, 0x00,
}
